### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by Prime-Crice** [brasov2de/ColorfulOptionsetGrid#38]
hello
https://uifabricicons.azurewebsites.net/ Json was configured as the friendly name of the homepage, but
comes out blank.

Example Icon 
![image](https://github.com/brasov2de/ColorfulOptionsetGrid/assets/65007615/ccfddf7d-d6e6-4c35-996e-4d51df5e774e)

Is there any way to fix that issue?

**Comment by brasov2de** [comment]
Would it be possible to provide the JSON configuration of the icons?

**Comment by Prime-Crice** [comment]
{"0": {"icon": "PowerAutomateLogo"},"1": {"icon": "PowerApps"},"2": {"icon": "PowerBILogo"},"3": {"icon": "Page"},"4": {"icon": "PowerVirtualAgentsLogo"}}

Here is my Json configuration.

**Comment by brasov2de** [comment]
It seems that there are differences in the icons library. I've posted the link you've used, because it's easier to search, but I guess not all the icons are there.
Please choose the icons from this link: https://developer.microsoft.com/en-us/fluentui#/styles/web/icons (you need to scroll down.
Unfortunatelly no PowerAutomateLogo is listed there
![image](https://github.com/brasov2de/ColorfulOptionsetGrid/assets/29977935/f8d705dc-9364-412e-8210-8048aecaf20a)

**Comment by Prime-Crice** [comment]
I will refer to that link.
Thank you for your help
